In [1]:
import numpy as np
np.array([4, 5, 6])

array([4, 5, 6])

In [2]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
an_array = np.array([1, 2, 3])
def double(x):
  return x * 2
mapped_array = double(an_array)
print(mapped_array)

[2 4 6]


In [4]:
squarer = lambda x: x * 2
vfunc = np.vectorize(squarer)
vfunc(an_array)

array([2, 4, 6])

In [5]:
from functools import reduce
np.union1d([-1, 0, 1], [-2, 0, 2])

array([-2, -1,  0,  1,  2])

In [6]:
reduce(np.union1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([1, 2, 3, 4, 6])

In [7]:
import numpy as np

a = np.arange(6)*2 
a

array([ 0,  2,  4,  6,  8, 10])

In [8]:
b = np.array([a, a*3])
b

array([[ 0,  2,  4,  6,  8, 10],
       [ 0,  6, 12, 18, 24, 30]])

In [9]:
b[0]

array([ 0,  2,  4,  6,  8, 10])

In [10]:
b[:, 1]

array([2, 6])

In [11]:
b[:, 1:2]

array([[2],
       [6]])

In [12]:
x = np.linspace(5, 15, 12)
x

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

In [13]:
x.ndim # 向量維度是3, 但張量維度是1

1

In [14]:
x.shape

(12,)

In [15]:
y = x.reshape(3, 4) # reshaping in general just provide another view on the same data
y

array([[ 5.        ,  5.90909091,  6.81818182,  7.72727273],
       [ 8.63636364,  9.54545455, 10.45454545, 11.36363636],
       [12.27272727, 13.18181818, 14.09090909, 15.        ]])

In [16]:
y.T # equal to y.transpose()

array([[ 5.        ,  8.63636364, 12.27272727],
       [ 5.90909091,  9.54545455, 13.18181818],
       [ 6.81818182, 10.45454545, 14.09090909],
       [ 7.72727273, 11.36363636, 15.        ]])

In [17]:
x = np.arange(15)
np.resize(x, (3, 1)) # resizing in general creates a new(temporary) object.

array([[0],
       [1],
       [2]])

In [18]:
np.resize(x, (1, 5))

array([[0, 1, 2, 3, 4]])

In [19]:
np.resize(x, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
np.resize(x, (5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [21]:
h = x.reshape(5, 3)
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [22]:
np.hstack((h, h*2))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [23]:
np.vstack((h, h*2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])